[project]
name = "traffic-analysis"
version = "0.1"
requires-python = ">=3.11"

dependencies = [
    "opencv-python==4.9.0.80", 
    "requests==2.31.0",
    "numpy==1.26.4",
     "matplotlib==3.6.2",
    "scipy>=1.12.0",
    "shapely==2.0.4",
    "pandas==2.2.2",
]
